application:
  version: 1.0.0

server:
  port: 1010

spring:
  servlet:
    multipart:
      enabled: true
  flyway:
    locations: classpath:db/migration
    table: schema_version
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    path: /api-docs


logging:
  level:
    default-logger: info

drone:
  periodicCheck: 60000 #periodic check for scheduled task
